apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-helm
      sync:
        infer:
          - "static/**.html"
deploy:
  helm:
    releases:
      - name: skaffold-helm
        chartPath: skaffold-helm
        values:
          image: gcr.io/k8s-skaffold/skaffold-helm
