replicaCount: 1
image: nginx:stable
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
  hosts:
    - chart-example.local
resources: {}
subchart:
  enabled: true
